-- =============================================
-- FULL DATABASE SETUP SCRIPT
-- Drop, create, and seed all tables
-- =============================================

DROP TABLE IF EXISTS meal_recipes;
DROP TABLE IF EXISTS meal_ingredients;
DROP TABLE IF EXISTS meals;

CREATE TABLE meals (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR NOT NULL,
    search_term     VARCHAR,
    goal            VARCHAR,
    diet_type       VARCHAR,
    tags            TEXT,
    default_servings INT NOT NULL DEFAULT 4
);

CREATE TABLE meal_ingredients (
    id           BIGSERIAL PRIMARY KEY,
    meal_id      BIGINT NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
    display_name VARCHAR NOT NULL,
    amount       VARCHAR,
    search_term  VARCHAR,
    min_price    DOUBLE PRECISION
);

CREATE TABLE meal_recipes (
    id          BIGSERIAL PRIMARY KEY,
    meal_id     BIGINT NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
    step_number INT NOT NULL,
    instruction TEXT NOT NULL
);

-- =============================================
-- SEED: meals
-- =============================================
INSERT INTO meals (name, search_term, goal, diet_type, tags) VALUES
('Kyllingfilet med ris og grønnsaker',   'kyllingfilet ris',         'healthy,muscle_gain',     'normal',  'høyprotein,rask,hverdagsmat'),
('Laksfilet med poteter og brokkoli',    'laksfilet poteter',        'healthy',                 'normal',  'omega3,middag,enkel'),
('Linsesuppe',                           'linsesuppe',               'healthy,weight_loss',     'vegan',   'budsjettvennlig,plantebasert,mettende'),
('Dampet brokkoli og kylling',           'brokkoli kylling dampet',  'healthy',                 'normal',  'lavkarbo,rask,høyprotein'),
('Tunfisksalat',                         'tunfisk salat',            'healthy,weight_loss',     'normal',  'rask,lunsj,lavkalorier'),
('Grønnsaksuppe',                        'grønnsaksuppe',            'weight_loss',             'vegan',   'lavkalorier,budsjettvennlig,plantebasert'),
('Tomatsuppe med brød',                  'tomatsuppe',               'weight_loss',             'vegetar', 'enkel,lunsj,varm'),
('Salat med egg og avokado',             'salat egg avokado',        'weight_loss',             'vegetar', 'lunsj,lavkarbo,mettende'),
('Eggerøre med laks og rugbrød',         'eggerøre laks',            'muscle_gain',             'normal',  'frokost,høyprotein,rask'),
('Omelett med skinke og ost',            'omelett skinke',           'muscle_gain',             'normal',  'frokost,høyprotein,lavkarbo'),
('Pasta med laks og fløtesaus',          'pasta laks fløte',         'muscle_gain',             'normal',  'middag,mettende,kremet'),
('Wok med kylling og nudler',            'wok kylling nudler',       'muscle_gain',             'normal',  'rask,asiatisk,hverdagsmat'),
('Havregrøt med bær og nøtter',          'havregrøt',                'healthy,weight_loss',     'vegan',   'frokost,fiber,budsjettvennlig'),
('Kyllingsuppe med grønnsaker',          'kyllingsuppe',             'healthy,weight_loss',     'normal',  'varm,hverdagsmat,mettende'),
('Bønnerøre med tortilla',               'bønner tortilla',          'weight_loss,muscle_gain', 'vegetar', 'rask,plantebasert,fyll'),
('Laks med quinoa og spinat',            'laks quinoa',              'healthy,muscle_gain',     'normal',  'høyprotein,omega3,treningsmåltid'),
('Gresk yoghurt med granola og honning', 'gresk yoghurt granola',    'healthy',                 'vegetar', 'frokost,rask,lettlaget'),
('Kjøttboller med tomatsaus og pasta',   'kjøttboller tomatsaus',    'muscle_gain',             'normal',  'klassiker,middag,mettende'),
('Blomkålsuppe',                         'blomkålsuppe',             'weight_loss',             'vegan',   'lavkalorier,plantebasert,kremete'),
('Stekt torsk med rotgrønnsaker',        'torsk rotgrønnsaker',      'healthy',                 'normal',  'sjømat,norsk,fiber');

-- =============================================
-- SEED: meal_ingredients
-- =============================================
INSERT INTO meal_ingredients (meal_id, display_name, amount, search_term, min_price) VALUES
(1,  'Kyllingfilet',         '600g',      'kyllingfilet',          69.90),
(1,  'Ris',                  '300g',      'ris langkorn',          12.00),
(1,  'Paprika',              '2 stk',     'paprika',               14.00),
(1,  'Brokkoli',             '1 hode',    'brokkoli',              18.00),
(1,  'Olivenolje',           '2 ss',      'olivenolje',            35.00),
(1,  'Salt og pepper',       'etter smak','salt pepper',            5.00),
(2,  'Laksfilet',            '500g',      'laksfilet',             89.00),
(2,  'Poteter',              '600g',      'poteter',               15.00),
(2,  'Brokkoli',             '1 hode',    'brokkoli',              18.00),
(2,  'Sitron',               '1 stk',     'sitron',                 7.00),
(2,  'Smør',                 '2 ss',      'smør meierismør',       22.00),
(3,  'Røde linser',          '300g',      'røde linser',           18.00),
(3,  'Gulrot',               '3 stk',     'gulrot',                 9.00),
(3,  'Løk',                  '1 stk',     'løk gul',                5.00),
(3,  'Hvitløk',              '3 fedd',    'hvitløk',                8.00),
(3,  'Hermetiske tomater',   '1 boks',    'hermetiske tomater',    12.00),
(3,  'Kokosmelk',            '1 boks',    'kokosmelk',             22.00),
(3,  'Karri',                '1 ts',      'karripulver',           15.00),
(4,  'Kyllingbryst',         '500g',      'kyllingbryst',          62.00),
(4,  'Brokkoli',             '2 hoder',   'brokkoli',              18.00),
(4,  'Soyasaus',             '2 ss',      'soyasaus',              18.00),
(4,  'Ingefær',              '1 ts',      'ingefær fersk',         12.00),
(4,  'Sesamolje',            '1 ss',      'sesamolje',             35.00),
(5,  'Tunfisk på boks',      '2 bokser',  'tunfisk vann',          28.00),
(5,  'Salat (isberg)',       '1 pose',    'isbergsalat',           18.00),
(5,  'Cherrytomater',        '250g',      'cherrytomater',         22.00),
(5,  'Agurk',                '1/2 stk',   'agurk',                 14.00),
(5,  'Rødløk',               '1/2 stk',   'rødløk',                 7.00),
(5,  'Olivenoljedressing',   '3 ss',      'olivenolje',            35.00),
(6,  'Gulrot',               '3 stk',     'gulrot',                 9.00),
(6,  'Sellerirot',           '1/2 stk',   'sellerirot',            18.00),
(6,  'Løk',                  '1 stk',     'løk gul',                5.00),
(6,  'Grønnkål',             '100g',      'grønnkål',              25.00),
(6,  'Grønnsakbuljong',      '1 l',       'grønnsakbuljong',       15.00),
(6,  'Erter (frosne)',       '200g',      'frosne erter',          18.00),
(7,  'Hermetiske tomater',   '2 bokser',  'hermetiske tomater',    12.00),
(7,  'Løk',                  '1 stk',     'løk gul',                5.00),
(7,  'Hvitløk',              '2 fedd',    'hvitløk',                8.00),
(7,  'Fløte',                '1 dl',      'matfløte',              24.00),
(7,  'Grovbrød',             '4 skiver',  'grovbrød',              28.00),
(7,  'Basilikum',            '1 ts',      'basilikum tørket',      18.00),
(8,  'Egg',                  '3 stk',     'egg frittgående',       28.00),
(8,  'Avokado',              '1 stk',     'avokado',               18.00),
(8,  'Blandingssalat',       '1 pose',    'blandingssalat',        22.00),
(8,  'Cherrytomater',        '150g',      'cherrytomater',         22.00),
(8,  'Olivenolje',           '2 ss',      'olivenolje',            35.00),
(8,  'Sitron',               '1/2 stk',   'sitron',                 7.00),
(9,  'Egg',                  '4 stk',     'egg frittgående',       28.00),
(9,  'Røkt laks',            '100g',      'røkt laks',             49.00),
(9,  'Rugbrød',              '4 skiver',  'rugbrød',               28.00),
(9,  'Smør',                 '1 ss',      'smør meierismør',       22.00),
(9,  'Gressløk',             '1/2 bunt',  'gressløk',              14.00),
(10, 'Egg',                  '4 stk',     'egg frittgående',       28.00),
(10, 'Kokt skinke',          '100g',      'kokt skinke',           35.00),
(10, 'Revet ost',            '50g',       'revet ost norvegia',    28.00),
(10, 'Melk',                 '2 ss',      'melk lettmelk',         16.00),
(10, 'Smør',                 '1 ss',      'smør meierismør',       22.00),
(10, 'Paprika',              '1/2 stk',   'paprika',               14.00),
(11, 'Laksfilet',            '400g',      'laksfilet',             89.00),
(11, 'Fusilli pasta',        '400g',      'fusilli pasta',         18.00),
(11, 'Matfløte',             '2 dl',      'matfløte',              24.00),
(11, 'Parmesan',             '50g',       'parmesan revet',        45.00),
(11, 'Hvitløk',              '2 fedd',    'hvitløk',                8.00),
(11, 'Dill',                 '1/2 bunt',  'dill fersk',            14.00),
(12, 'Kyllingfilet',         '500g',      'kyllingfilet',          69.90),
(12, 'Nudler (egg)',         '300g',      'eggenudler',            22.00),
(12, 'Paprika',              '2 stk',     'paprika',               14.00),
(12, 'Sukkererter',          '150g',      'sukkererter',           28.00),
(12, 'Soyasaus',             '3 ss',      'soyasaus',              18.00),
(12, 'Sesamolje',            '1 ss',      'sesamolje',             35.00),
(12, 'Ingefær',              '1 ss',      'ingefær fersk',         12.00),
(13, 'Havregryn',            '100g',      'havregryn lettkokt',    12.00),
(13, 'Melk',                 '3 dl',      'melk lettmelk',         16.00),
(13, 'Frosne blandingsbær',  '100g',      'frosne bær blanding',   28.00),
(13, 'Valnøtter',            '30g',       'valnøtter',             39.00),
(13, 'Honning',              '1 ss',      'honning',               35.00),
(14, 'Kyllingbryst',         '400g',      'kyllingbryst',          62.00),
(14, 'Gulrot',               '3 stk',     'gulrot',                 9.00),
(14, 'Purre',                '1 stk',     'purre',                 18.00),
(14, 'Selleri',              '2 stilker', 'selleri',               22.00),
(14, 'Kyllingbuljong',       '1.5 l',     'kyllingbuljong',        15.00),
(14, 'Persillerot',          '1 stk',     'persillerot',           14.00),
(15, 'Sorte bønner',         '2 bokser',  'sorte bønner hermetisk',18.00),
(15, 'Hvetetortilla',        '4 stk',     'hvetetortilla',         28.00),
(15, 'Rødløk',               '1 stk',     'rødløk',                 7.00),
(15, 'Paprika',              '1 stk',     'paprika',               14.00),
(15, 'Rømme',                '2 ss',      'rømme lettrømme',       22.00),
(15, 'Limejuice',            '1/2 stk',   'lime',                   8.00),
(15, 'Koriander',            '1/2 bunt',  'koriander fersk',       14.00),
(16, 'Laksfilet',            '500g',      'laksfilet',             89.00),
(16, 'Quinoa',               '200g',      'quinoa',                38.00),
(16, 'Babyspinat',           '150g',      'babyspinat',            28.00),
(16, 'Sitron',               '1 stk',     'sitron',                 7.00),
(16, 'Olivenolje',           '2 ss',      'olivenolje',            35.00),
(16, 'Hvitløk',              '2 fedd',    'hvitløk',                8.00),
(17, 'Gresk yoghurt 10%',    '400g',      'gresk yoghurt',         28.00),
(17, 'Granola',              '80g',       'granola havre',         35.00),
(17, 'Honning',              '2 ss',      'honning',               35.00),
(17, 'Frosne bær',           '100g',      'frosne bær blanding',   28.00),
(18, 'Kjøttboller',          '500g',      'kjøttboller ferdig',    65.00),
(18, 'Penne pasta',          '400g',      'penne pasta',           18.00),
(18, 'Hermetiske tomater',   '2 bokser',  'hermetiske tomater',    12.00),
(18, 'Løk',                  '1 stk',     'løk gul',                5.00),
(18, 'Hvitløk',              '3 fedd',    'hvitløk',                8.00),
(18, 'Revet parmesan',       '50g',       'parmesan revet',        45.00),
(18, 'Basilikum',            '1 ts',      'basilikum tørket',      18.00),
(19, 'Blomkål',              '1 hode',    'blomkål',               28.00),
(19, 'Løk',                  '1 stk',     'løk gul',                5.00),
(19, 'Hvitløk',              '2 fedd',    'hvitløk',                8.00),
(19, 'Grønnsakbuljong',      '1 l',       'grønnsakbuljong',       15.00),
(19, 'Kokosmelk',            '1 boks',    'kokosmelk',             22.00),
(19, 'Karri',                '1 ts',      'karripulver',           15.00),
(20, 'Torskefilet',          '600g',      'torskefilet',           85.00),
(20, 'Gulrot',               '4 stk',     'gulrot',                 9.00),
(20, 'Pastinakk',            '2 stk',     'pastinakk',             18.00),
(20, 'Rødbete',              '2 stk',     'rødbete',               14.00),
(20, 'Olivenolje',           '3 ss',      'olivenolje',            35.00),
(20, 'Timian',               '1 ts',      'timian tørket',         15.00),
(20, 'Sitron',               '1 stk',     'sitron',                 7.00);

-- =============================================
-- SEED: meal_recipes
-- =============================================
INSERT INTO meal_recipes (meal_id, step_number, instruction) VALUES
(1, 1, 'Skjær kyllingfilet i biter og krydre med salt og pepper.'),
(1, 2, 'Kok risen i lettsaltet vann etter anvisning på pakken.'),
(1, 3, 'Skjær paprika og brokkoli i biter.'),
(1, 4, 'Stek kyllingen i olivenolje på middels varme til gjennomstekt, ca 8 minutter.'),
(1, 5, 'Tilsett grønnsakene og stek videre i 5 minutter til de er møre men fremdeles har litt tyggemotstand.'),
(1, 6, 'Server kylling og grønnsaker over risen.'),
(2, 1, 'Skrell potetene, del i biter og kok i lettsaltet vann i ca 15 minutter.'),
(2, 2, 'Del brokkoli i buketter og kok i 5 minutter til myk men sprø.'),
(2, 3, 'Krydre laksfilet med salt, pepper og sitronsaft.'),
(2, 4, 'Stek laksen i smør på middels-høy varme, ca 3–4 minutter per side.'),
(2, 5, 'Server laks med poteter og brokkoli, og legg sitronskiver ved siden.'),
(3, 1, 'Finhakk løk og hvitløk. Skrell og skjær gulrot i terninger.'),
(3, 2, 'Fres løk og hvitløk i litt olje i en stor kjele til de er myke.'),
(3, 3, 'Tilsett karri og fres under omrøring i 1 minutt.'),
(3, 4, 'Tilsett linser, hermetiske tomater og kokosmelk. Hell over 8 dl vann.'),
(3, 5, 'Kok opp og la surre på lav varme i 25 minutter til linsene er helt møre.'),
(3, 6, 'Smak til med salt og pepper. Server gjerne med flatbrød.'),
(4, 1, 'Skjær kyllingbryst i jevne biter, krydre med salt og pepper.'),
(4, 2, 'Del brokkoli i buketter.'),
(4, 3, 'Damp brokkolien i en dampkurv over kokende vann i ca 6 minutter.'),
(4, 4, 'Varm sesamolje i panne på middels-høy varme og stek kyllingen til gjennomstekt.'),
(4, 5, 'Tilsett soyasaus og revet ingefær, rør godt og la koke inn i 1 minutt.'),
(4, 6, 'Server kylling over dampet brokkoli.'),
(5, 1, 'Skyll og tørk salatbladene, riv i passe store biter.'),
(5, 2, 'Del cherrytomater i to. Skjær agurk i skiver og rødløk i tynne ringer.'),
(5, 3, 'Hell av olje/vann fra tunfiskboksene og smul fisken.'),
(5, 4, 'Bland alle ingredienser i en stor salatbolle.'),
(5, 5, 'Dryss over olivenoljedressing og smak til med salt og pepper. Server umiddelbart.'),
(6, 1, 'Skrell og skjær gulrot og sellerirot i terninger. Hakk løk.'),
(6, 2, 'Fres løk i litt olje i en stor kjele til gjennomsiktig.'),
(6, 3, 'Tilsett gulrot og sellerirot, fres i 3 minutter under omrøring.'),
(6, 4, 'Hell over grønnsakbuljong og kok opp. La surre i 20 minutter.'),
(6, 5, 'Tilsett frosne erter og hakket grønnkål, kok videre i 5 minutter.'),
(6, 6, 'Smak til med salt og pepper og server varm.'),
(7, 1, 'Finhakk løk og hvitløk.'),
(7, 2, 'Fres løk og hvitløk i litt olje til myke og blanke.'),
(7, 3, 'Tilsett hermetiske tomater og basilikum. La surre i 10 minutter.'),
(7, 4, 'Kjør suppen jevn med stavmikser direkte i kjelen.'),
(7, 5, 'Rør inn fløten og varm forsiktig opp uten å koke. Smak til med salt og pepper.'),
(7, 6, 'Server suppen med grovbrødskiver ved siden.'),
(8, 1, 'Kok eggene hardkokte i 9 minutter. Avkjøl under kaldt vann og skrell.'),
(8, 2, 'Skjær avokado i skiver og press sitronjuice over for å hindre bruning.'),
(8, 3, 'Skyll og tørk salatbladene.'),
(8, 4, 'Arranger salat og cherrytomater i en bolle. Legg avokadoskiver og delte egg på toppen.'),
(8, 5, 'Dryss over olivenolje og smak til med salt og pepper. Server umiddelbart.'),
(9, 1, 'Visp eggene sammen med en klype salt og pepper.'),
(9, 2, 'Smelt smøret i en panne på middels varme.'),
(9, 3, 'Hell i eggene og rør forsiktig med slikkepott til kremet og akkurat stivnet eggerøre.'),
(9, 4, 'Rist rugbrødskivene i brødrister eller panne.'),
(9, 5, 'Legg eggerøre på brødskivene, topp med røkt laks og klippet gressløk.'),
(10, 1, 'Visp egg med melk, salt og pepper i en bolle.'),
(10, 2, 'Skjær skinke og paprika i biter.'),
(10, 3, 'Smelt smør i en panne på middels varme.'),
(10, 4, 'Hell i eggeblandingen og la stivne rolig fra kantene innover, ca 3 minutter.'),
(10, 5, 'Fordel skinke, paprika og revet ost på halve omeletten.'),
(10, 6, 'Brett den andre halvdelen over fyllet og server straks.'),
(11, 1, 'Kok pasta etter anvisning på pakken i lettsaltet vann. Hell av.'),
(11, 2, 'Skjær laksfilet i biter, ca 3×3 cm.'),
(11, 3, 'Finhakk hvitløk og fres i litt olje i en dyp panne.'),
(11, 4, 'Tilsett matfløte og kok opp under omrøring.'),
(11, 5, 'Legg i laksebitene og la trekke i sausen på lav varme i 5 minutter.'),
(11, 6, 'Bland inn kokt pasta og dill. Topp med revet parmesan og server.'),
(12, 1, 'Kok nudler etter anvisning. Skyll i kaldt vann og sett til side.'),
(12, 2, 'Skjær kylling i strimler. Skjær paprika i strimler.'),
(12, 3, 'Varm sesamolje i en wok på høy varme til det ryker lett.'),
(12, 4, 'Stek kyllingstrimlene raskt til gjennomstekte, ca 5 minutter. Ta ut av woken.'),
(12, 5, 'Wok paprika og sukkererter i 3 minutter til sprø-møre.'),
(12, 6, 'Legg kylling og nudler tilbake i woken. Tilsett soyasaus og revet ingefær, rør godt og server.'),
(13, 1, 'Ha havregryn i en kjele og tilsett melk.'),
(13, 2, 'Kok opp under omrøring og la surre på lav varme i 5 minutter. Rør jevnlig.'),
(13, 3, 'Tin blandingsbærene lett i mikrobølgeovn (1 min) eller la stå i romtemperatur.'),
(13, 4, 'Hell grøten i skåler. Topp med bær, grovhakkede valnøtter og honning. Server varm.'),
(14, 1, 'Skjær kyllingbryst i terninger. Skrell og skjær gulrot i skiver. Skjær purre og selleri i biter.'),
(14, 2, 'Brun kyllingbitene i litt olje i en stor kjele, ca 3 minutter.'),
(14, 3, 'Tilsett gulrot, purre og selleri, fres i ytterligere 3 minutter.'),
(14, 4, 'Hell over kyllingbuljong og kok opp. Tilsett persillerot.'),
(14, 5, 'La surre på lav varme i 25 minutter til grønnsakene er møre. Smak til med salt og pepper.'),
(15, 1, 'Hell av lake fra bønnene og skyll godt i et dørslag.'),
(15, 2, 'Finhakk rødløk og skjær paprika i terninger.'),
(15, 3, 'Varm bønnene i en kjele med litt olje. Mos dem lett med en gaffel.'),
(15, 4, 'Bland inn rødløk, paprika og limejuice. Smak til med salt og pepper.'),
(15, 5, 'Varm tortillaene i en tørr panne, ca 30 sekunder per side.'),
(15, 6, 'Fyll tortillaene med bønnerøre, rømme og frisk koriander. Brett og server.'),
(16, 1, 'Skyll quinoa grundig i kaldt vann. Kok etter anvisning (ca 15 min) med dobbel mengde vann.'),
(16, 2, 'Finhakk hvitløk og fres i olivenolje i en panne.'),
(16, 3, 'Legg i laksfilet, krydre med salt og pepper, stek 3–4 minutter per side.'),
(16, 4, 'Ha babyspinat i pannen og la falle sammen i 1 minutt.'),
(16, 5, 'Server laks over quinoa med spinat ved siden. Press fersk sitron over.'),
(17, 1, 'Ta bærene ut av fryseren og la dem tine i 10 minutter.'),
(17, 2, 'Del yoghurten i serveringsskåler.'),
(17, 3, 'Dryss granola jevnt over yoghurten.'),
(17, 4, 'Fordel tinede bær på toppen og dryss over honning. Server umiddelbart.'),
(18, 1, 'Kok pasta etter anvisning på pakken i lettsaltet vann. Hell av.'),
(18, 2, 'Finhakk løk og hvitløk. Fres i litt olje i en dyp panne til myke.'),
(18, 3, 'Tilsett hermetiske tomater og basilikum. La surre i 10 minutter under omrøring.'),
(18, 4, 'Brun kjøttbollene i en separat panne i litt olje til de er gjennomvarme.'),
(18, 5, 'Legg kjøttbollene i tomatsausen og bland forsiktig.'),
(18, 6, 'Server over pasta med revet parmesan på toppen.'),
(19, 1, 'Del blomkålen i buketter. Hakk løk og hvitløk.'),
(19, 2, 'Fres løk og hvitløk i litt olje i en stor kjele til myke.'),
(19, 3, 'Tilsett karri og fres i 1 minutt under omrøring.'),
(19, 4, 'Tilsett blomkål og grønnsakbuljong. Kok opp og la surre i 20 minutter til blomkålen er helt myk.'),
(19, 5, 'Rør inn kokosmelk. Kjør suppen jevn med stavmikser.'),
(19, 6, 'Smak til med salt og pepper. Server varm, gjerne med brød til.'),
(20, 1, 'Forvarm ovnen til 200°C.'),
(20, 2, 'Skrell gulrot, pastinakk og rødbete. Skjær i jevne biter.'),
(20, 3, 'Vend rotgrønnsakene i olivenolje, timian, salt og pepper. Fordel på en stekeplate.'),
(20, 4, 'Stek grønnsakene i ovnen i 25–30 minutter til de er møre og lett karamelliserte.'),
(20, 5, 'Krydre torskefilet med salt, pepper og sitronsaft. Stek i stekepanne i smør, 3–4 minutter per side.'),
(20, 6, 'Server torsken med de ovnsstekte rotgrønnsakene og sitronbåter ved siden.');