DROP TABLE IF EXISTS meal_ingredients;
DROP TABLE IF EXISTS meals;

CREATE TABLE meals (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR NOT NULL,
    search_term VARCHAR,
    goal        VARCHAR,
    diet_type   VARCHAR,
    tags        TEXT
);

CREATE TABLE meal_ingredients (
    id           SERIAL PRIMARY KEY,
    meal_id      INT NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
    display_name VARCHAR NOT NULL,
    amount       VARCHAR,
    search_term  VARCHAR,
    min_price    DOUBLE PRECISION
);

INSERT INTO meals (name, search_term, goal, diet_type, tags) VALUES
('Kyllingfilet med ris og grønnsaker',   'kyllingfilet ris',         'healthy,muscle_gain',          'normal',   'høyprotein,rask,hverdagsmat'),
('Laksfilet med poteter og brokkoli',    'laksfilet poteter',        'healthy',                      'normal',   'omega3,middag,enkel'),
('Linsesuppe',                           'linsesuppe',               'healthy,weight_loss',          'vegan',    'budsjettvennlig,plantebasert,mettende'),
('Dampet brokkoli og kylling',           'brokkoli kylling dampet',  'healthy',                      'normal',   'lavkarbo,rask,høyprotein'),
('Tunfisksalat',                         'tunfisk salat',            'healthy,weight_loss',          'normal',   'rask,lunsj,lavkalorier'),
('Grønnsaksuppe',                        'grønnsaksuppe',            'weight_loss',                  'vegan',    'lavkalorier,budsjettvennlig,plantebasert'),
('Tomatsuppe med brød',                  'tomatsuppe',               'weight_loss',                  'vegetar',  'enkel,lunsj,varm'),
('Salat med egg og avokado',             'salat egg avokado',        'weight_loss',                  'vegetar',  'lunsj,lavkarbo,mettende'),
('Eggerøre med laks og rugbrød',         'eggerøre laks',            'muscle_gain',                  'normal',   'frokost,høyprotein,rask'),
('Omelett med skinke og ost',            'omelett skinke',           'muscle_gain',                  'normal',   'frokost,høyprotein,lavkarbo'),
('Pasta med laks og fløtesaus',          'pasta laks fløte',         'muscle_gain',                  'normal',   'middag,mettende,kremet'),
('Wok med kylling og nudler',            'wok kylling nudler',       'muscle_gain',                  'normal',   'rask,asiatisk,hverdagsmat'),
('Havregrøt med bær og nøtter',          'havregrøt',                'healthy,weight_loss',          'vegan',    'frokost,fiber,budsjettvennlig'),
('Kyllingsuppe med grønnsaker',          'kyllingsuppe',             'healthy,weight_loss',          'normal',   'varm,hverdagsmat,mettende'),
('Bønnerøre med tortilla',               'bønner tortilla',          'weight_loss,muscle_gain',      'vegetar',  'rask,plantebasert,fyll'),
('Laks med quinoa og spinat',            'laks quinoa',              'healthy,muscle_gain',          'normal',   'høyprotein,omega3,treningsmåltid'),
('Gresk yoghurt med granola og honning', 'gresk yoghurt granola',    'healthy',                      'vegetar',  'frokost,rask,lettlaget'),
('Kjøttboller med tomatsaus og pasta',   'kjøttboller tomatsaus',    'muscle_gain',                  'normal',   'klassiker,middag,mettende'),
('Blomkålsuppe',                         'blomkålsuppe',             'weight_loss',                  'vegan',    'lavkalorier,plantebasert,kremete'),
('Stekt torsk med rotgrønnsaker',        'torsk rotgrønnsaker',      'healthy',                      'normal',   'sjømat,norsk,fiber');

INSERT INTO meal_ingredients (meal_id, display_name, amount, search_term, min_price) VALUES
(1, 'Kyllingfilet',         '600g',      'kyllingfilet',          69.90),
(1, 'Ris',                  '300g',      'ris langkorn',          12.00),
(1, 'Paprika',              '2 stk',     'paprika',               14.00),
(1, 'Brokkoli',             '1 hode',    'brokkoli',              18.00),
(1, 'Olivenolje',           '2 ss',      'olivenolje',            35.00),
(1, 'Salt og pepper',       'etter smak','salt pepper',            5.00),
(2, 'Laksfilet',            '500g',      'laksfilet',             89.00),
(2, 'Poteter',              '600g',      'poteter',               15.00),
(2, 'Brokkoli',             '1 hode',    'brokkoli',              18.00),
(2, 'Sitron',               '1 stk',     'sitron',                 7.00),
(2, 'Smør',                 '2 ss',      'smør meierismør',       22.00),
(3, 'Røde linser',          '300g',      'røde linser',           18.00),
(3, 'Gulrot',               '3 stk',     'gulrot',                 9.00),
(3, 'Løk',                  '1 stk',     'løk gul',                5.00),
(3, 'Hvitløk',              '3 fedd',    'hvitløk',                8.00),
(3, 'Hermetiske tomater',   '1 boks',    'hermetiske tomater',    12.00),
(3, 'Kokosmelk',            '1 boks',    'kokosmelk',             22.00),
(3, 'Karri',                '1 ts',      'karripulver',           15.00),
(4, 'Kyllingbryst',         '500g',      'kyllingbryst',          62.00),
(4, 'Brokkoli',             '2 hoder',   'brokkoli',              18.00),
(4, 'Soyasaus',             '2 ss',      'soyasaus',              18.00),
(4, 'Ingefær',              '1 ts',      'ingefær fersk',         12.00),
(4, 'Sesamolje',            '1 ss',      'sesamolje',             35.00),
(5, 'Tunfisk på boks',      '2 bokser',  'tunfisk vann',          28.00),
(5, 'Salat (isberg)',       '1 pose',    'isbergsalat',           18.00),
(5, 'Cherrytomater',        '250g',      'cherrytomater',         22.00),
(5, 'Agurk',                '1/2 stk',   'agurk',                 14.00),
(5, 'Rødløk',               '1/2 stk',   'rødløk',                 7.00),
(5, 'Olivenoljedressing',   '3 ss',      'olivenolje',            35.00),
(6, 'Gulrot',               '3 stk',     'gulrot',                 9.00),
(6, 'Sellerirot',           '1/2 stk',   'sellerirot',            18.00),
(6, 'Løk',                  '1 stk',     'løk gul',                5.00),
(6, 'Grønnkål',             '100g',      'grønnkål',              25.00),
(6, 'Grønnsakbuljong',      '1 l',       'grønnsakbuljong',       15.00),
(6, 'Erter (frosne)',       '200g',      'frosne erter',          18.00),
(7, 'Hermetiske tomater',   '2 bokser',  'hermetiske tomater',    12.00),
(7, 'Løk',                  '1 stk',     'løk gul',                5.00),
(7, 'Hvitløk',              '2 fedd',    'hvitløk',                8.00),
(7, 'Fløte',                '1 dl',      'matfløte',              24.00),
(7, 'Grovbrød',             '4 skiver',  'grovbrød',              28.00),
(7, 'Basilikum',            '1 ts',      'basilikum tørket',      18.00),
(8, 'Egg',                  '3 stk',     'egg frittgående',       28.00),
(8, 'Avokado',              '1 stk',     'avokado',               18.00),
(8, 'Blandingssalat',       '1 pose',    'blandingssalat',        22.00),
(8, 'Cherrytomater',        '150g',      'cherrytomater',         22.00),
(8, 'Olivenolje',           '2 ss',      'olivenolje',            35.00),
(8, 'Sitron',               '1/2 stk',   'sitron',                 7.00),
(9, 'Egg',                  '4 stk',     'egg frittgående',       28.00),
(9, 'Røkt laks',            '100g',      'røkt laks',             49.00),
(9, 'Rugbrød',              '4 skiver',  'rugbrød',               28.00),
(9, 'Smør',                 '1 ss',      'smør meierismør',       22.00),
(9, 'Gressløk',             '1/2 bunt',  'gressløk',              14.00),
(10, 'Egg',                 '4 stk',     'egg frittgående',       28.00),
(10, 'Kokt skinke',         '100g',      'kokt skinke',           35.00),
(10, 'Revet ost',           '50g',       'revet ost norvegia',    28.00),
(10, 'Melk',                '2 ss',      'melk lettmelk',         16.00),
(10, 'Smør',                '1 ss',      'smør meierismør',       22.00),
(10, 'Paprika',             '1/2 stk',   'paprika',               14.00),
(11, 'Laksfilet',           '400g',      'laksfilet',             89.00),
(11, 'Fusilli pasta',       '400g',      'fusilli pasta',         18.00),
(11, 'Matfløte',            '2 dl',      'matfløte',              24.00),
(11, 'Parmesan',            '50g',       'parmesan revet',        45.00),
(11, 'Hvitløk',             '2 fedd',    'hvitløk',                8.00),
(11, 'Dill',                '1/2 bunt',  'dill fersk',            14.00),
(12, 'Kyllingfilet',        '500g',      'kyllingfilet',          69.90),
(12, 'Nudler (egg)',        '300g',      'eggenudler',            22.00),
(12, 'Paprika',             '2 stk',     'paprika',               14.00),
(12, 'Sukkererter',         '150g',      'sukkererter',           28.00),
(12, 'Soyasaus',            '3 ss',      'soyasaus',              18.00),
(12, 'Sesamolje',           '1 ss',      'sesamolje',             35.00),
(12, 'Ingefær',             '1 ss',      'ingefær fersk',         12.00),
(13, 'Havregryn',           '100g',      'havregryn lettkokt',    12.00),
(13, 'Melk',                '3 dl',      'melk lettmelk',         16.00),
(13, 'Frosne blandingsbær', '100g',      'frosne bær blanding',   28.00),
(13, 'Valnøtter',           '30g',       'valnøtter',             39.00),
(13, 'Honning',             '1 ss',      'honning',               35.00),
(14, 'Kyllingbryst',        '400g',      'kyllingbryst',          62.00),
(14, 'Gulrot',              '3 stk',     'gulrot',                 9.00),
(14, 'Purre',               '1 stk',     'purre',                 18.00),
(14, 'Selleri',             '2 stilker', 'selleri',               22.00),
(14, 'Kyllingbuljong',      '1.5 l',     'kyllingbuljong',        15.00),
(14, 'Persillerot',         '1 stk',     'persillerot',           14.00),
(15, 'Sorte bønner',        '2 bokser',  'sorte bønner hermetisk',18.00),
(15, 'Hvetetortilla',       '4 stk',     'hvetetortilla',         28.00),
(15, 'Rødløk',              '1 stk',     'rødløk',                 7.00),
(15, 'Paprika',             '1 stk',     'paprika',               14.00),
(15, 'Rømme',               '2 ss',      'rømme lettrømme',       22.00),
(15, 'Limejuice',           '1/2 stk',   'lime',                   8.00),
(15, 'Koriander',           '1/2 bunt',  'koriander fersk',       14.00),
(16, 'Laksfilet',           '500g',      'laksfilet',             89.00),
(16, 'Quinoa',              '200g',      'quinoa',                38.00),
(16, 'Babyspinat',          '150g',      'babyspinat',            28.00),
(16, 'Sitron',              '1 stk',     'sitron',                 7.00),
(16, 'Olivenolje',          '2 ss',      'olivenolje',            35.00),
(16, 'Hvitløk',             '2 fedd',    'hvitløk',                8.00),
(17, 'Gresk yoghurt 10%',   '400g',      'gresk yoghurt',         28.00),
(17, 'Granola',             '80g',       'granola havre',         35.00),
(17, 'Honning',             '2 ss',      'honning',               35.00),
(17, 'Frosne bær',          '100g',      'frosne bær blanding',   28.00),
(18, 'Kjøttboller',         '500g',      'kjøttboller ferdig',    65.00),
(18, 'Penne pasta',         '400g',      'penne pasta',           18.00),
(18, 'Hermetiske tomater',  '2 bokser',  'hermetiske tomater',    12.00),
(18, 'Løk',                 '1 stk',     'løk gul',                5.00),
(18, 'Hvitløk',             '3 fedd',    'hvitløk',                8.00),
(18, 'Revet parmesan',      '50g',       'parmesan revet',        45.00),
(18, 'Basilikum',           '1 ts',      'basilikum tørket',      18.00),
(19, 'Blomkål',             '1 hode',    'blomkål',               28.00),
(19, 'Løk',                 '1 stk',     'løk gul',                5.00),
(19, 'Hvitløk',             '2 fedd',    'hvitløk',                8.00),
(19, 'Grønnsakbuljong',     '1 l',       'grønnsakbuljong',       15.00),
(19, 'Kokosmelk',           '1 boks',    'kokosmelk',             22.00),
(19, 'Karri',               '1 ts',      'karripulver',           15.00),
(20, 'Torskefilet',         '600g',      'torskefilet',           85.00),
(20, 'Gulrot',              '4 stk',     'gulrot',                 9.00),
(20, 'Pastinakk',           '2 stk',     'pastinakk',             18.00),
(20, 'Rødbete',             '2 stk',     'rødbete',               14.00),
(20, 'Olivenolje',          '3 ss',      'olivenolje',            35.00),
(20, 'Timian',              '1 ts',      'timian tørket',         15.00),
(20, 'Sitron',              '1 stk',     'sitron',                 7.00);