spring.application.name=planabite-backend
kassalapp.api.key=DIN_KASSALAPP_API_NØKKEL

spring.datasource.url=jdbc:postgresql://localhost:5432/planabite
spring.datasource.username=DITT_POSTGRES_BRUKERNAVN
spring.datasource.password=DITT_POSTGRES_PASSORD
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect