spring.application.name=planabite-backend
<<<<<<< HEAD
kassalapp.api.key=lSD5KQJr3LmBOzMHdjexXqaqC4WsYgUccIFKvUbA
=======
kassalapp.api.key=your_kassalapp_api_key_here
spoonacular.api.key=your_spoonacular_api_key_here
>>>>>>> f19a9760d6658d1b444331042040346fb576e4b2
